const fileInput=document.getElementById("fileInput"),dropZone=document.getElementById("dropZone"),editor=document.getElementById("editor"),fileList=document.getElementById("fileList"),fileCount=document.getElementById("fileCount"),clearBtn=document.getElementById("clearBtn"),format=document.getElementById("format"),pageSize=document.getElementById("pageSize"),widthInput=document.getElementById("width"),heightInput=document.getElementById("height"),quality=document.getElementById("quality"),qualityValue=document.getElementById("qualityValue"),keepRatio=document.getElementById("keepRatio"),convertBtn=document.getElementById("convertBtn"),progress=document.getElementById("progress"),progressBar=progress.querySelector("span"),status=document.getElementById("status");let files=[];
function isHeic(file){return /\\.(heic|heif)$/i.test(file.name)||/image\\/(heic|heif)/i.test(file.type)}
function isP65(file){return /\\.p65$/i.test(file.name)||/pagemaker/i.test(file.type)}
function formatBytes(n){if(n<1024)return n+" B";if(n<1048576)return(n/1024).toFixed(1)+" KB";return(n/1048576).toFixed(1)+" MB"}
function addFiles(list){const incoming=Array.from(list).filter(f=>f.type.startsWith("image/")||/\.(jpe?g|png|webp|heic|heif)$/i.test(f.name));files=[...files,...incoming];render();if(!incoming.length)status.textContent="Please choose an image file (JPG, PNG, WebP or HEIC)."}
function render(){fileList.innerHTML="";files.forEach((file,i)=>{const item=document.createElement("div");item.className="file-item";const img=document.createElement("img");img.className="thumb";img.alt="";if(!isHeic(file)&&!isP65(file))img.src=URL.createObjectURL(file);else img.src="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='44' height='44'%3E%3Crect width='44' height='44' rx='8' fill='%23eef1f6'/%3E%3Ctext x='22' y='27' text-anchor='middle' font-family='Arial' font-size='11' fill='%23687585'%3EHEIC%3C/text%3E%3C/svg%3E";const name=document.createElement("span");name.className="file-name";name.textContent=file.name;const size=document.createElement("span");size.className="file-size";size.textContent=formatBytes(file.size);const remove=document.createElement("button");remove.className="remove";remove.textContent="×";remove.onclick=()=>{files.splice(i,1);render()};item.append(img,name,size,remove);fileList.appendChild(item)});fileCount.textContent=files.length+" file"+(files.length===1?"":"s");editor.classList.toggle("hidden",files.length===0)}
fileInput.onchange=e=>addFiles(e.target.files);["dragenter","dragover"].forEach(ev=>dropZone.addEventListener(ev,e=>{e.preventDefault();dropZone.classList.add("drag")}));["dragleave","drop"].forEach(ev=>dropZone.addEventListener(ev,e=>{e.preventDefault();dropZone.classList.remove("drag")}));dropZone.addEventListener("drop",e=>addFiles(e.dataTransfer.files));dropZone.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();fileInput.click()}});clearBtn.onclick=()=>{files=[];fileInput.value="";render();status.textContent=""};quality.oninput=()=>qualityValue.textContent=quality.value+"%";format.onchange=()=>pageSize.disabled=format.value!=="pdf";
function loadImage(file){return new Promise(async(resolve,reject)=>{try{let blob=file;if(isHeic(file)){if(typeof heic2any!=="function")throw new Error("HEIC converter library did not load.");blob=await heic2any({blob:file,toType:"image/jpeg",quality:.95});if(Array.isArray(blob))blob=blob[0]}const url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("Could not read "+file.name))};img.src=url}catch(e){reject(e)}})}
function resizedCanvas(img){let w=img.naturalWidth||img.width,h=img.naturalHeight||img.height,tw=parseInt(widthInput.value,10),th=parseInt(heightInput.value,10);if(tw>0||th>0){if(keepRatio.checked){if(tw>0){w=tw;h=Math.max(1,Math.round(img.height/img.width*w))}else{h=th;w=Math.max(1,Math.round(img.width/img.height*h))}}else{w=tw>0?tw:w;h=th>0?th:h}}const c=document.createElement("canvas");c.width=w;c.height=h;const ctx=c.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,w,h);ctx.drawImage(img,0,0,w,h);return c}
function canvasBlob(canvas,type,q){return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error("Could not create output.")),type,q))}function safeName(n){return n.replace(/\.[^.]+$/,"").replace(/[^a-z0-9_-]+/gi,"-")||"converted"}function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000)}
async function convertP65(file){
  throw new Error("P65 engine is not built yet. Run the GitHub Action 'Build P65 converter' once, then reload this page.");
}
async function makePdf(){const {jsPDF}=window.jspdf;const sizes={a4:[210,297],a5:[148,210],letter:[216,279]};let pdf=null;for(let i=0;i<files.length;i++){status.textContent="Converting "+(i+1)+" of "+files.length+"...";const img=await loadImage(files[i]),canvas=resizedCanvas(img);let wmm,hmm;if(pageSize.value==="original"){wmm=210;hmm=Math.max(1,210*(canvas.height/canvas.width))}else{[wmm,hmm]=sizes[pageSize.value];if(canvas.width>canvas.height)[wmm,hmm]=[hmm,wmm]}if(!pdf)pdf=new jsPDF({orientation:wmm>hmm?"landscape":"portrait",unit:"mm",format:[wmm,hmm]});else pdf.addPage([wmm,hmm],wmm>hmm?"landscape":"portrait");pdf.addImage(canvas.toDataURL("image/jpeg",Number(quality.value)/100),"JPEG",0,0,wmm,hmm,undefined,"FAST");progressBar.style.width=((i+1)/files.length*100)+"%"}download(pdf.output("blob"),"converted-images.pdf")}
async function makeImages(){const mime={jpeg:"image/jpeg",png:"image/png",webp:"image/webp"}[format.value],ext=format.value==="jpeg"?"jpg":format.value;for(let i=0;i<files.length;i++){status.textContent="Converting "+(i+1)+" of "+files.length+"...";const img=await loadImage(files[i]),canvas=resizedCanvas(img),blob=await canvasBlob(canvas,mime,format.value==="png"?undefined:Number(quality.value)/100);download(blob,safeName(files[i].name)+"."+ext);progressBar.style.width=((i+1)/files.length*100)+"%"}}
convertBtn.onclick=async()=>{if(!files.length)return;convertBtn.disabled=true;progress.classList.remove("hidden");progressBar.style.width="0%";try{if(files.some(isP65)){if(files.length!==1||!isP65(files[0]))throw new Error("For P65, select one .p65 file at a time.");await convertP65(files[0]);}else if(format.value==="pdf")await makePdf();else await makeImages();status.textContent="Done — your download is ready."}catch(e){console.error(e);status.textContent="Conversion failed: "+e.message}finally{convertBtn.disabled=false}};format.onchange();